// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    ElButton: typeof import('element-plus/es')['ElButton']
    ElCollapse: typeof import('element-plus/es')['ElCollapse']
    ElCollapseItem: typeof import('element-plus/es')['ElCollapseItem']
    ElContainer: typeof import('element-plus/es')['ElContainer']
    ElDrawer: typeof import('element-plus/es')['ElDrawer']
    ElHeader: typeof import('element-plus/es')['ElHeader']
    ElInput: typeof import('element-plus/es')['ElInput']
    ElMain: typeof import('element-plus/es')['ElMain']
    FilterDrawer: typeof import('./src/components/FilterDrawer.vue')['default']
    FloatPanel: typeof import('./src/components/FloatPanel.vue')['default']
    MainPage: typeof import('./src/components/MainPage.vue')['default']
    MusicItem: typeof import('./src/components/MusicItem.vue')['default']
    SelectList: typeof import('./src/components/SelectList.vue')['default']
    StatPanel: typeof import('./src/components/statPanel.vue')['default']
  }
  export interface ComponentCustomProperties {
    vLoading: typeof import('element-plus/es')['ElLoadingDirective']
  }
}
