// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/core/pull/3399
import "@vue/runtime-core";

export {};

declare module "@vue/runtime-core" {
    export interface GlobalComponents {
        ElAffix: typeof import("element-plus/es")["ElAffix"];
        ElContainer: typeof import("element-plus/es")["ElContainer"];
        ElHeader: typeof import("element-plus/es")["ElHeader"];
        ElInput: typeof import("element-plus/es")["ElInput"];
        ElMain: typeof import("element-plus/es")["ElMain"];
        ElPageHeader: typeof import("element-plus/es")["ElPageHeader"];
        FloatPanel: typeof import("./src/components/FloatPanel.vue")["default"];
        MainPage: typeof import("./src/components/MainPage.vue")["default"];
        MusicItem: typeof import("./src/components/MusicItem.vue")["default"];
        StatPanel: typeof import("./src/components/statPanel.vue")["default"];
    }
}
